input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => {
      "service" => "smart-activity-tracker"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "smart-activity-tracker-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
